### ISSUE TITLE
Form submission remove ajax submit input

### ISSUE THREAD

**Issue by caleb-smith-capstorm** [Hube2/wpforms-ajax-submit#1]
If you submit a form and the form submission was rejected, WPForms is sending back a json object with the content of the original form.

When the container.empty() / container.append() lines in wpforms-ajax-submit.js, around line 68 is called it wipes out the modifications from the document.ready() and the ajax URL target will bomb out due to the missing wpforms_ajax_submit action.

To fix, add the lines:

```
form = $('#'+form_id).get(0);
$(form).attr('action', 'javascript: wpforms_ajax_submit("'+form_id+'");');
$(form).append('<input type="hidden" name="action" value="wpforms_ajax_submit" />');
```
after:
```
if (json['content']) {
  container.empty();
  container.append(json['content']);
```

**Comment by Hube2** [comment]
Good catch, and thank you for letting me know. I will work on this ASAP.

**Comment by Hube2** [comment]
I have added your suggested code, it looks great. Let me know if you find any other issues.

~JH
